# Generated by Django 3.1.3 on 2020-11-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jingdian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('open_time', models.CharField(max_length=20)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.type')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
