# Generated by Django 3.1.3 on 2020-11-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201110_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jingdian',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['pk']},
        ),
    ]
