# Generated by Django 3.1.3 on 2020-11-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201111_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jingdian',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
