# Generated by Django 3.1.3 on 2020-11-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201111_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jingdian',
            name='open_time',
            field=models.TextField(),
        ),
    ]
